### ISSUE TITLE
Add 3 new doormats to the home page template

### ISSUE THREAD

**Issue by DK-TBS** [ServiceCanada/GCWeb#12]
[http://servicecanada.github.io/GCWeb/home-en.html](http://servicecanada.github.io/GCWeb/home-en.html)

Latest version of the spec requires 3 new doormats added below the ones already there.  They'll be for 3 GC-Wide audiences:  Seniors, Aboriginals, Veterans.  

Maybe we can just use filler text for the descriptions of the new doormats for now... not sure who would be responsible for writing those up.

**Comment by shawnthompson** [comment]
I was thinking about maybe removing the homepage from the sample page in general. The only domain that should have the homepage is the actual Canada.ca domain and none of the partners. These templates are to show the "partners" sample pages of the templates that are going on Canada.ca...

Thoughts?

**Comment by DK-TBS** [comment]
Agree!  I guess there's pretty much zero departments who will ever need to have access to the homepage template... so if you want to rip it out of the demo templates area, it's probably safe.  

On the other hand, I suppose you might find it useful to have in there as sort of a dev version of the homepage that you can tinker with.  Whatever you think is best.

Say, who should we be talking to about getting the actual, live canada.ca homepage geared up with the three audience doormats, anyway?  Is it someone at servicecan who would be writing and publishing those to the live site?

**Comment by DK-TBS** [comment]
closing this issue, because I just recreated it on web-boew repo
