### ISSUE TITLE
Region

### ISSUE THREAD

**Issue by shawnthompson** [ServiceCanada/GCWeb#4]
[Region](http://servicecanada.github.io/GCWeb/contact/region-en.html)

Wasn't to sure that to do with the "Location" column so I just added a placeholder image for now. By the looks in the specs they wanted it to be smaller than the left column but the image dimensions for that side were setup for a half page grid, might want a bigger image on the left to allow for a smaller one on the right. Also leaving the geomap for last because it will take me the longest to get done. Might need @masterbee help.

I used definition list for the contact info and service hours for semantics responsive reasons. Unfortunately they float the text to the right.

![capture3](https://cloud.githubusercontent.com/assets/2575266/5856722/a812ca98-a213-11e4-82ed-4a10d4463548.JPG)

**Comment by shawnthompson** [comment]
How about not having the info on the same line? while keeping the semantics
![capture](https://cloud.githubusercontent.com/assets/2575266/6153010/60f42c7e-b1ef-11e4-87ca-957f336cd154.JPG)

**Comment by DK-TBS** [comment]
Agree!  This layout looks better for sure.

**Comment by DK-TBS** [comment]
* Let’s remove the square brackets around the “[Locations]” heading, that one’s not a placeholder

* Can we trim down the height of that location map?  Ideally the two columns would be about the same height

* Let’s add a colon after “This office can assist with the following”

* We should probably remove the brackets around the telephone number.  Also, the official standard format for phone numbers is XXX-XXX-XXXX, with a hyphen between the area code and the rest

**Comment by shawnthompson** [comment]
How does this look for the width of the map? It's a little off because of the instructions above the map that were added for accessibility controls.

![screen shot 2015-02-25 at 3 14 45 pm](https://cloud.githubusercontent.com/assets/2575266/6379544/13947480-bd01-11e4-9c4e-b8c832dcd22a.png)

**Comment by DK-TBS** [comment]
The width seems cool, I'm sure a 50/50 split like that will do just fine.  Any chance we can trim a few pixels off the height to sort of compensate for the instructions being in there?  I know we'll never get the two sides to line up exactly, but if we could get it a little closer that would be an improvement...
