### ISSUE TITLE
Topics – lowest level topic page

### ISSUE THREAD

**Issue by shawnthompson** [ServiceCanada/GCWeb#6]
I don't see anything to create here, all I see is it's talking about a section of the Topics page.

[screen shot 2015-01-23 at 9 35 25 am](https://cloud.githubusercontent.com/assets/2575266/5876188/34ae7874-a2e3-11e4-8f24-03e1a695e141.png)

**Comment by DK-TBS** [comment]
This one is all sorted out now, no more changes from our end on the lowest level subtopic page.
